# Generated by Django 4.1.7 on 2023-04-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered_date',
        ),
    ]
